### ISSUE TITLE
0. Setup backend boilerplate

### ISSUE THREAD

**Issue by riboney** [riboney/Outdeed#1]
**Subtasks**
- [x] Setup express app configuration
- [x] Setup mongoose driver configuration
- [x] Setup Project file structure
- [x] Setup Logger
  - [x] Log to file
  - [x] Log to console
- [x] Setup env
- [x] Setup unit testing
- [x] Setup precommit githook
- [x] Setup linters
- [x] Dockerize development environment
- [x] Create health check route

**Done**
- Start up express server
  -  Running on port defined in environment variable
  - Express connection logged in console
  - MongoDB connection logged in console
- `/health` endpoint:
  - Server runtime
  - MongoDB stats
  - GET request info in logged console
- Run tests
  - `/health` returns 200 response
- Stop git commit if style violations exists
