### ISSUE TITLE
Setup daisyUI and implement style guide

### ISSUE THREAD

**Issue by riboney** [riboney/Outdeed#13]
**Subtasks**
- [x] Install & setup daisyUI
- [x] Install & setup @tailwindcss/typography plugin
- [x] Add google fonts as shown in style guide
- [x] Configure color palette as shown in style guide

**Done**
- using `prose` auto applies typographic styling
- able to use style guide fonts in tailwind
- able to use style guide colors in tailwind
