### ISSUE TITLE
0. Setup Figma & design system

### ISSUE THREAD

**Issue by riboney** [riboney/Outdeed#3]
**Subtasks**

- [x] Create style guide
  - [x] Choose fonts
    - [x] Display
    - [x] Headings
    - [x] Body
  - [x] Choose color palette
- [x] Setup Figma library
  - [x] Setup color palette
  - [x] Setup fonts
  - [x] Setup components
    - [x] Buttons
    - [x] Input fields

**Done**
- Figma workspace ready for development
- Style guide present in `/docs`
