### ISSUE TITLE
0. Setup API error handling

### ISSUE THREAD

**Issue by riboney** [riboney/Outdeed#6]
**Subtasks**

- [x] Middlewares
  - [x] Catch any error and return custom response
  - [x] Be able to catch specific errors such as API errors, mongodb errors, etc and return custom response
  - [x] Install express-async-errors
- [x] Create custom APIError type for all api-related errors
- [x] Create DTO guard to catch invalid POST payloads and prevent MongoDB save exceptions
- [x] Handle lengthy request operations by timing out requests and throwing error

**Done**
- Can use APIError provide detailed error responses
- Can use DTO guard to throw error during `create` operations to prevent MongoDB from saving invalid entities
- Application can catch specific errors and can returns custom error responses
- Be able to write async requests and handle async errors without needing to user verbose try/catch
- Time out requests that take too long and return proper error response
