### ISSUE TITLE
0. Setup Mongoose utils

### ISSUE THREAD

**Issue by riboney** [riboney/Outdeed#7]
**Subtasks**

- [x] Create model/ schema factory method
- [x] Create MongoDB id validation util function
- [x] Create schema attribute extraction util functions

**Done**
- Can create MongoDB documents/ models with ModelFactory function
- Can verify ids as valid MongoDB ObjectIds
- Can extract attributes (all or required only)  from mongoose models
